import assert from "node:assert/strict";
import { SendStatus, type SendResult } from "../src/shell/sendStatus.ts";
import { Workspace } from "../src/shell/workspace.ts";

const pending: { channel: string; resolve: (r: SendResult) => void; reject: (e: unknown) => void }[] = [];
let paints = 0;
const status = new SendStatus((channel) => new Promise((resolve, reject) => pending.push({ channel, resolve, reject })), () => { paints++; });
const workspace = new Workspace({ getItem: () => null, setItem: () => {} }, () => 1, () => {});
const draft = workspace.putDraft("alpha", { text: "old", reply: { id: "parent", login: "alice", text: "hi" }, start: 3, end: 3 });
const first = status.submit("alpha", draft);
assert.equal(status.get("alpha")?.state, "queued");
assert.equal(await status.submit("alpha", draft), undefined, "double click cannot enqueue twice");
const beta = status.submit("beta", { ...draft, text: "beta" });
assert.deepEqual(pending.map((p) => p.channel), ["alpha", "beta"], "another tab can send while alpha waits");
workspace.putDraft("alpha", { ...draft, text: "new" });
pending[0].resolve({ status: "transmitted" });
assert.equal((await first)?.status, "transmitted");
assert.equal(workspace.clearAccepted("alpha", draft), false, "late completion preserves edits in its channel");
pending[1].reject({ code: "error.message.send_failed" });
assert.equal(await beta, undefined);
assert.equal(status.get("beta")?.state, "error");
const retry = status.submit("beta", status.get("beta")!.draft);
pending[2].resolve({ status: "sent", messageId: "twitch-real-id" });
assert.equal((await retry)?.messageId, "twitch-real-id");
assert.equal(status.get("beta")?.state, "sent");
const uncertain = status.submit("alpha", draft);
pending[3].reject({ code: "error.message.send_unknown" });
await uncertain;
assert.equal(status.get("alpha")?.state, "unknown");
status.forget("alpha");
assert.equal(status.get("alpha"), undefined);
assert.equal(paints, 8);
console.log("sendStatus tests ok");
