import assert from "node:assert/strict";
import { Workspace, WORKSPACE_KEY } from "../src/shell/workspace.ts";

let raw: string | null = null;
let writes = 0;
const callbacks = new Map<number, () => void>();
let id = 0;
const storage = { getItem: () => raw, setItem: (_key: string, value: string) => { raw = value; writes += 1; } };
const make = () => new Workspace(storage, (fn) => { callbacks.set(++id, fn); return id; }, (n) => { callbacks.delete(n); });
const a = { text: "alpha draft", reply: { id: "parent-1", login: "alice", text: "question" }, start: 3, end: 5 };
const b = { text: "beta draft", reply: null, start: 4, end: 4 };
const workspace = make();
const sent = workspace.putDraft("#ALPHA", a);
workspace.putDraft("beta", b);
workspace.putScroll("alpha", { atBottom: false, rowsFromBottom: 17, anchor: { msgId: "message-22", offsetFrac: .4 } });
assert.equal(callbacks.size, 1, "typing/scroll saves coalesce");
workspace.flush();
assert.equal(writes, 1);
assert.equal(callbacks.size, 0);
const restarted = make();
assert.deepEqual(restarted.draft("alpha"), { ...a, revision: 0 });
assert.deepEqual(restarted.draft("beta"), { ...b, revision: 0 });
assert.deepEqual(restarted.scroll("alpha"), { atBottom: false, rowsFromBottom: 17, anchor: { msgId: "message-22", offsetFrac: .4 } });
const returned = workspace.draft("alpha");
returned.reply!.id = "tampered";
assert.equal(workspace.draft("alpha").reply?.id, "parent-1", "read snapshots cannot mutate stored reply");
workspace.putDraft("alpha", { ...a, text: "edited" });
workspace.putDraft("alpha", a);
assert.equal(workspace.clearAccepted("alpha", sent), false, "edit then revert still owns a new revision");
const latest = workspace.draft("alpha");
workspace.putDraft("alpha", { ...a, start: 0, end: 0 });
assert.equal(workspace.clearAccepted("alpha", latest), true, "selection alone does not change draft identity");
assert.equal(workspace.draft("beta").text, b.text, "clearing accepted alpha does not touch beta");
workspace.retain(["beta"]);
workspace.flush();
assert.equal(make().draft("alpha").reply, null, "closed tabs stay removed on reboot");
assert.equal(make().draft("beta").text, b.text);
for (let n = 0; n < 30; n++) workspace.putDraft(`channel${n}`, b);
workspace.flush();
assert.equal(JSON.parse(raw!).channels.length, 20, "workspace has bounded retention");
raw = "not json";
assert.equal(make().draft("alpha").text, "");
raw = JSON.stringify({ version: 1, channels: [{ channel: "alpha", draft: { text: "abc", reply: { id: "bad\nid" }, start: -10, end: 9999 }, scroll: { atBottom: false, rowsFromBottom: -1, anchor: { msgId: "a", offsetFrac: 50 } } }] });
const sanitized = make();
assert.equal(sanitized.draft("alpha").reply, null);
assert.equal(sanitized.draft("alpha").start, 0);
assert.equal(sanitized.draft("alpha").end, 3);
assert.equal(sanitized.scroll("alpha")?.anchor?.offsetFrac, 1);
let failure = true;
let errors = 0;
const failing = new Workspace({ getItem: () => null, setItem: (key, value) => { assert.equal(key, WORKSPACE_KEY); if (failure) throw new Error("disk full"); raw = value; } }, (fn) => { callbacks.set(++id, fn); return id; }, (n) => { callbacks.delete(n); });
failing.onError = () => { errors++; };
failing.putDraft("alpha", a);
failing.flush();
assert.equal(errors, 1);
assert.equal(failing.draft("alpha").text, a.text);
failure = false;
failing.flush();
assert.equal(make().draft("alpha").text, a.text, "failed disk save remains dirty and can retry");
console.log("workspace tests ok");
