/**
 * Writes WCAG contrast matrix to ../.cursor/audit/contrast.md (parent of tauri-app).
 * Run: npm run test:contrast-report
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  WCAG_AA_TEXT,
  WCAG_AA_UI,
  contrastRatio,
  passesAaText,
  passesAaUi,
} from "../src/shell/themeContrast.ts";
import { listThemePresets, themeTokens } from "../src/shell/theme.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "..", ".cursor", "audit");
const outFile = join(outDir, "contrast.md");

type BgKey = "windowBg" | "surface1" | "surface2" | "surface3";
const BGS: { key: BgKey; label: string }[] = [
  { key: "windowBg", label: "window" },
  { key: "surface1", label: "surface-1" },
  { key: "surface2", label: "surface-2" },
  { key: "surface3", label: "surface-3" },
];

const TEXT = [
  { key: "windowText" as const, label: "text" },
  { key: "muted" as const, label: "muted" },
];
const UI = [
  { key: "accent" as const, label: "accent" },
  { key: "danger" as const, label: "danger" },
  { key: "success" as const, label: "success" },
  { key: "warning" as const, label: "warning" },
  { key: "focusRing" as const, label: "focusRing" },
];

function cell(fg: string, bg: string, kind: "text" | "ui"): string {
  const r = contrastRatio(fg, bg);
  const ok = kind === "text" ? passesAaText(fg, bg) : passesAaUi(fg, bg);
  const mark = ok ? "PASS" : "FAIL";
  return `${r.toFixed(2)} ${mark}`;
}

const lines: string[] = [
  "# Theme contrast audit (WCAG AA)",
  "",
  `Text ≥ ${WCAG_AA_TEXT}:1 · UI ≥ ${WCAG_AA_UI}:1`,
  "",
  "Generated by `npm run test:contrast-report`.",
  "",
];

let fails = 0;
for (const preset of listThemePresets()) {
  const t = themeTokens(preset);
  lines.push(`## ${preset}`);
  lines.push("");
  lines.push(
    `| Token | ${BGS.map((b) => b.label).join(" | ")} |`,
  );
  lines.push(`| --- | ${BGS.map(() => "---").join(" | ")} |`);
  for (const row of TEXT) {
    const cells = BGS.map((b) => {
      const s = cell(t[row.key], t[b.key], "text");
      if (s.endsWith("FAIL")) {
        fails += 1;
      }
      return s;
    });
    lines.push(`| ${row.label} (\`${t[row.key]}\`) | ${cells.join(" | ")} |`);
  }
  for (const row of UI) {
    const cells = BGS.map((b) => {
      const s = cell(t[row.key], t[b.key], "ui");
      if (s.endsWith("FAIL")) {
        fails += 1;
      }
      return s;
    });
    lines.push(`| ${row.label} (\`${t[row.key]}\`) | ${cells.join(" | ")} |`);
  }
  lines.push("");
}

lines.push(fails === 0 ? "**Result: all PASS.**" : `**Result: ${fails} FAIL.**`);
lines.push("");

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, lines.join("\n"), "utf8");
console.log(`wrote ${outFile} (${fails} fail)`);
process.exit(fails === 0 ? 0 : 1);
